# Generated by Django 3.0.5 on 2020-05-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toukoukeijibanapp', '0002_auto_20200519_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, choices=[['0', '北海道']], max_length=10, null=True, verbose_name='都道府県'),
        ),
    ]
